### ISSUE TITLE
Setup Wizard cant connect to Wifi

### ISSUE THREAD

**Issue by grimanos** [crdroidandroid/android#125]
I built a rom for my phone!!! On the first boot while on SetupWizard i am unable to connect to Wifi. If i skip the setup and then connect to wifi from Settings and resume the Setup Wizard from the notification i can continue the setup. Here is the logs i get when this happens:

--------- beginning of main
2023-06-24 06:20:28.251 22897-22897 Choreographer           com.google.android.setupwizard       W  Frame time is 0.023335 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2023-06-24 06:21:48.360 22897-22897 Choreographer           com.google.android.setupwizard       W  Frame time is 0.011028 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
2023-06-24 06:22:00.506 22897-23021 SetupLibrary            com.google.android.setupwizard       W  [SetupCompatServiceInvoker] Report focusChange failed since service reference is null. Are the permission valid?
2023-06-24 06:22:34.813 22897-23021 SetupLibrary            com.google.android.setupwizard       W  [SetupCompatServiceInvoker] logMetric failed since service reference is null. Are the permissions valid?
2023-06-24 06:22:34.814 22897-22897 SetupWizard             com.google.android.setupwizard       I  [WifiEntryDialogFragment] Try Connecting failed. isAdded=true, is future null=false, connectionRequestSubmitted=true
2023-06-24 06:22:34.825 22897-22928 OpenGLRenderer          com.google.android.setupwizard       E  Unable to match the desired swap behavior.
2023-06-24 06:22:34.947 22897-23021 SetupLibrary            com.google.android.setupwizard       W  [SetupCompatServiceInvoker] Report focusChange failed since service reference is null. Are the permission valid?
2023-06-24 06:22:37.516 22897-22897 SetupWizard             com.google.android.setupwizard       I  [WifiEntryMonitor] User requested connecting to access point=buc@797a810
2023-06-24 06:22:37.516 22897-22897 SetupWizard             com.google.android.setupwizard       I  [bts] WifiDialogHandlerFragment attached.
2023-06-24 06:22:37.583 22897-23021 SetupLibrary            com.google.android.setupwizard       W  [SetupCompatServiceInvoker] Report focusChange failed since service reference is null. Are the permission valid?
2023-06-24 06:22:41.222 22897-22897 SetupWizard             com.google.android.setupwizard       I  [WifiEntryDialogFragment] Received response from WifiDialogActivity. resultCode=1
2023-06-24 06:22:41.223 22897-22897 SetupWizard             com.google.android.setupwizard       W  [WifiEntryDialogFragment] WifiConfig is null!
2023-06-24 06:22:41.223 22897-22897 SetupWizard             com.google.android.setupwizard       E  [WifiEntryDialogFragment] Connected access point not found in scan results
2023-06-24 06:22:41.233 22897-23021 SetupLibrary            com.google.android.setupwizard       W  [SetupCompatServiceInvoker] logMetric failed since service reference is null. Are the permissions valid?
2023-06-24 06:22:41.233 22897-22897 SetupWizard             com.google.android.setupwizard       I  [WifiEntryDialogFragment] Try Connecting failed. isAdded=true, is future null=false, connectionRequestSubmitted=true
2023-06-24 06:22:41.235 22897-22897 SetupWizard             com.google.android.setupwizard       W  [bsr] Error connecting to access point
                                                                                                    bta
                                                                                                    	at bud.e(PG:4)
                                                                                                    	at bts.onResume(PG:2)
                                                                                                    	at android.app.Fragment.performResume(Fragment.java:2551)
                                                                                                    	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
                                                                                                    	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
                                                                                                    	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
                                                                                                    	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
                                                                                                    	at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3014)
                                                                                                    	at android.app.FragmentController.dispatchResume(FragmentController.java:207)
                                                                                                    	at android.app.Activity.performResume(Activity.java:8496)
                                                                                                    	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4763)
                                                                                                    	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4806)
                                                                                                    	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:179)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2023-06-24 06:22:41.262 22897-23021 SetupLibrary            com.google.android.setupwizard       W  [SetupCompatServiceInvoker] Report focusChange failed since service reference is null. Are the permission valid?
2023-06-24 06:23:04.103 22897-22897 PhenotypeBackgroundRecv com.google.android.setupwizard       I  Skipping com.google.android.setupwizard which doesn't use ProcessStable flags.
2023-06-24 06:24:42.893 22897-23021 SetupLibrary            com.google.android.setupwizard       W  [SetupCompatServiceInvoker] Report focusChange failed since service reference is null. Are the permission valid?
2023-06-24 06:25:12.832 22897-23474 PhenotypeProcessReaper  com.google.android.setupwizard       I  Memory state is: 125

**Comment by ShevT** [comment]
This problem is on the side of GApps.
In my firmware, I solved it [like this](https://gitlab.com/ShevT/android_vendor_gapps/-/commit/6cf30e6cababdf5b3e03f1e4e3db92edd71a7968).

**Comment by grimanos** [comment]
Do I have to update only the android.bp or everything you change on the commit??

**Comment by ShevT** [comment]
If you collect the firmware, then everything that I changed is desirable. 
In general, my repository is my analogue of MindGapps
