### ISSUE TITLE
Camera crashes when opening from another app

### ISSUE THREAD

**Issue by konaya** [crdroidandroid/android#90]
When another app tries to take a photo (for instance, a web browser using the Camera to form upload a photo), the camera crashes. The crash log is as shown below:

```
time: 1648554548027
msg: java.lang.UnsupportedOperationException: Stream configuration not supported
stacktrace: java.lang.UnsupportedOperationException: Stream configuration not supported
	at hcs.get(Unknown Source:188)
	at rkz.get(Unknown Source:73)
	at han.get(Unknown Source:76)
	at rkz.get(Unknown Source:73)
	at hal.get(Unknown Source:72)
	at rkz.get(Unknown Source:73)
	at hba.a(Unknown Source:24)
	at haz.run(Unknown Source:41)
	at mtb.run(Unknown Source:21)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at qwt.c(Unknown Source:21)
	at qvu.run(Unknown Source:938)
	at qwu.run(Unknown Source:9)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at mto.run(Unknown Source:13)
	at mtn.run(Unknown Source:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
	at msf.run(Unknown Source:7)
```

OnePlus 9 pro, cdDroid 7.15 (lemonadep)

**Comment by gwolf2u** [comment]
7.x is deprecated now for OP9Pro
Update to newer 8.x
